### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by ilium007** [ryzhovau/ryzhovau#1]
Hi - just wanting to know if I can still get the CFE code you published a long time ago

http://github.com/downloads/ryzhovau/asuswrt-ryzhov/cfe_n66u-1.0.1.3-4.tgz

Thanks!

**Comment by ryzhovau** [comment]
Please, tell me where did you get this link? I'll fix it.

http://files.ryzhov-al.ru/Routers/RT-N66U_CFE_update/

**Comment by ilium007** [comment]
Hi - the link was in a number of ancient threads relating to the RT-N66U. I was just trying to get an old one set up as a wireless bridge.

https://www.snbforums.com/threads/cfe-bootloader-update.8259/page-16

https://deviwiki.com/wiki/ASUS_RT-N66U/CFE_bootloader_update

As it turned out, I found your cfe_n66u-1.0.1.9.tgz  file but after running the script under Asus-merlin and testing with `nvram set clkfreq=300 && nvram commit && reboot` the setting did not stick with the 1.0.1.9 CFE.
